export interface FoodCompareItem {
  id: string;
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  category: string;
  description: string;
  healthGrade: 'A' | 'B' | 'C' | 'D' | 'F';
  advice: string;
  swapWith?: string;
}

export const PAKISTANI_FOODS_DB_EXPANDED: FoodCompareItem[] = [
  { 
    id: "roti", 
    name: "Whole-wheat Chapati / Roti (1 medium)", 
    calories: 120, 
    protein: 4.2, 
    carbs: 24, 
    fat: 0.8, 
    fiber: 3.5, 
    category: "Breads", 
    description: "Traditional flatbread prepared using stone-ground whole wheat (Lal Atta).",
    healthGrade: 'A',
    advice: "An excellent baseline carbohydrate source packed with magnesium and complex fibers that regulate sugar release."
  },
  { 
    id: "paratha", 
    name: "Plain Paratha (1 medium)", 
    calories: 290, 
    protein: 5.0, 
    carbs: 36, 
    fat: 14.5, 
    fiber: 1.2, 
    category: "Breads", 
    description: "Flaky traditional flatbread rolled and shallow-fried in hydrogenated ghee or cooking oil.",
    healthGrade: 'D',
    advice: "High in trans fats and calories. Swapping this for a dry whole-wheat chapati saves 170 kcal per meal and protects arteries.",
    swapWith: "roti"
  },
  { 
    id: "paratha-aloo", 
    name: "Aloo Paratha (1 medium)", 
    calories: 360, 
    protein: 6.2, 
    carbs: 48, 
    fat: 16.0, 
    fiber: 2.5, 
    category: "Breads", 
    description: "Flatbread stuffed with spiced mashed potatoes and griddle-fried in oil.",
    healthGrade: 'F',
    advice: "Extremely dense in simple starches and frying oils, causing immediate insulin spikes. Swap for single dry Roti or high-protein eggs.",
    swapWith: "roti"
  },
  { 
    id: "naan-maida", 
    name: "White Flour Naan (1 piece)", 
    calories: 310, 
    protein: 8.5, 
    carbs: 61, 
    fat: 3.5, 
    fiber: 1.5, 
    category: "Breads", 
    description: "Tandoor-baked leavened bread made with bleached white flour (Maida).",
    healthGrade: 'D',
    advice: "Refined flour has had all its essential fiber and zinc stripped away. Rapidly degrades glycemic index controls. Swap for whole wheat chapati.",
    swapWith: "roti"
  },
  { 
    id: "rice-white", 
    name: "White Basmati Rice (1 cup cooked)", 
    calories: 205, 
    protein: 4.2, 
    carbs: 45, 
    fat: 0.4, 
    fiber: 0.6, 
    category: "Grains", 
    description: "Polished long-grain rice with starch coat, highly popular in regional main courses.",
    healthGrade: 'C',
    advice: "Polished rice spikes blood glucose rapidly. Control portions or combine with generous high-fiber lentils (Daal) or green salads."
  },
  { 
    id: "rice-brown", 
    name: "Brown Basmati Rice (1 cup cooked)", 
    calories: 215, 
    protein: 5.0, 
    carbs: 45, 
    fat: 1.6, 
    fiber: 3.5, 
    category: "Grains", 
    description: "Whole-grain rice with its fibrous bran and nutrient-rich germ layer preserved.",
    healthGrade: 'A',
    advice: "Maintains a lower glycemic profile than white rice. Abundant in magnesium and B vitamins to support active muscle metabolism.",
    swapWith: "rice-brown"
  },
  { 
    id: "biryani", 
    name: "Chicken Biryani (1 plate / 250g)", 
    calories: 460, 
    protein: 24, 
    carbs: 64, 
    fat: 13.5, 
    fiber: 2.0, 
    category: "Meals", 
    description: "Layered fragrant spiced rice and chicken, cooked with ghee and saffron coloring.",
    healthGrade: 'C',
    advice: "High in sodium and fats. Eating this in moderation with a large side of cucumber raita and limiting rice portions is highly advised."
  },
  { 
    id: "haleem-beef", 
    name: "Beef Haleem (1 bowl / 250g)", 
    calories: 340, 
    protein: 26, 
    carbs: 38, 
    fat: 11.0, 
    fiber: 7.5, 
    category: "Meals", 
    description: "Slow-cooked savory paste made of shredded beef, barley, whole wheat, and various lentils.",
    healthGrade: 'B',
    advice: "Highly nutritious and exceptionally high in slow-digesting proteins and dietary fiber. Limit external ghee tarka to keep fats low."
  },
  { 
    id: "nihari-beef", 
    name: "Beef Nihari (1 portion with gravy)", 
    calories: 520, 
    protein: 34, 
    carbs: 12, 
    fat: 38.0, 
    fiber: 0.8, 
    category: "Meals", 
    description: "Heavy slow-cooked shank beef stew garnished with bone marrow, ginger, and oil floating tarka layer.",
    healthGrade: 'F',
    advice: "Extremely rich in saturated fats and sodium. Puts significant load on cardiovascular structures. Swap for lean Chicken Tikka or Haleem.",
    swapWith: "haleem-beef"
  },
  { 
    id: "chicken-karahi", 
    name: "Chicken Karahi (1 portion)", 
    calories: 350, 
    protein: 28, 
    carbs: 6, 
    fat: 22.0, 
    fiber: 1.2, 
    category: "Meals", 
    description: "Chicken breast and bone-in pieces cooked in a heavy tomato, ginger, garlic, and chili oil base.",
    healthGrade: 'C',
    advice: "Gravy is typically prepared in excess oil. To make it a health powerhouse, drain oil off or prepare home-cooked using 1 tsp of olive oil."
  },
  { 
    id: "chicken-tikka", 
    name: "Chicken Tikka Boti (1 skewer / 150g)", 
    calories: 190, 
    protein: 31, 
    carbs: 2, 
    fat: 6.5, 
    fiber: 0.0, 
    category: "Meals", 
    description: "Skinless chicken breast chunks marinated in lemon, yogurt, spices, and open-flame charcoal grilled.",
    healthGrade: 'A',
    advice: "An absolute gold standard for clean, low-fat lean protein. Exceptionally low in carbohydrates, supporting rapid cardiovascular healing."
  },
  { 
    id: "daal-cooked", 
    name: "Yellow split Daal (1 cup cooked)", 
    calories: 180, 
    protein: 8.5, 
    carbs: 29, 
    fat: 3.5, 
    fiber: 6.2, 
    category: "Sides", 
    description: "Cooked split mung/masoor lentils simmered with turmeric and garlic.",
    healthGrade: 'A',
    advice: "Abundant in folate and iron. Soluble fibers bind bile acids to help naturally lower bad LDL cholesterol levels in the blood."
  },
  { 
    id: "sabzi-mixed", 
    name: "Mixed Vegetable Sabzi (1 cup)", 
    calories: 140, 
    protein: 3.0, 
    carbs: 18, 
    fat: 6.0, 
    fiber: 4.5, 
    category: "Sides", 
    description: "Sautéed seasonal okra, peas, potatoes, and carrots seasoned with regional spices.",
    healthGrade: 'B',
    advice: "Highly nutritious due to diverse phytonutrients. Ensure minimal oil (tarka) is used to preserve low caloric density."
  },
  { 
    id: "samosa-fried", 
    name: "Deep-Fried Samosa (1 piece)", 
    calories: 250, 
    protein: 4.0, 
    carbs: 22, 
    fat: 15.0, 
    fiber: 1.0, 
    category: "Snacks", 
    description: "Bleached flour dough stuffed with potato starches and deep-fried in oxidized frying oils.",
    healthGrade: 'F',
    advice: "Dense in trans fats and simple carbohydrates. Deep frying damages lipid structures. Swap for roasted chickpeas or a baked alternative.",
    swapWith: "chana-roasted"
  },
  { 
    id: "samosa-baked", 
    name: "Baked Veggie Samosa (1 piece)", 
    calories: 130, 
    protein: 3.8, 
    carbs: 18, 
    fat: 3.2, 
    fiber: 1.8, 
    category: "Snacks", 
    description: "Thin pastry with potato and pea stuffing, oven-baked to bypass heavy frying oils.",
    healthGrade: 'B',
    advice: "Saves over 120 calories and eliminates toxic trans-fats completely while preserving the classic flavor.",
    swapWith: "samosa-baked"
  },
  { 
    id: "chana-roasted", 
    name: "Dry Roasted Chana (Bhuna Chana, 30g)", 
    calories: 110, 
    protein: 6.2, 
    carbs: 18, 
    fat: 1.8, 
    fiber: 5.5, 
    category: "Snacks", 
    description: "Dry roasted whole black chickpeas, eaten traditional shell-on or peeled.",
    healthGrade: 'A',
    advice: "An outstanding, portable super-snack! Packed with iron, folate, and slow-release low-GI fiber that completely blunts hunger."
  },
  { 
    id: "shami-kabab", 
    name: "Beef/Chicken Shami Kabab (1 piece)", 
    calories: 170, 
    protein: 13.5, 
    carbs: 5, 
    fat: 9.5, 
    fiber: 1.8, 
    category: "Sides", 
    description: "Lentil (Chana daal) and spiced minced meat patty, lightly pan-seared.",
    healthGrade: 'B',
    advice: "Provides clean muscle-repairing proteins. Prepare using minimal oil spray or air-fry to restrict calorie load."
  },
  { 
    id: "egg-boiled", 
    name: "Boiled Egg (1 whole)", 
    calories: 72, 
    protein: 6.3, 
    carbs: 0.4, 
    fat: 4.8, 
    fiber: 0.0, 
    category: "Breakfast", 
    description: "Hard or soft-boiled chicken egg containing complete amino-acid profiling.",
    healthGrade: 'A',
    advice: "Egg whites are pure bioavailable albumin protein. The yolk is highly rich in memory-enhancing choline and vitamin D."
  },
  { 
    id: "dahi-plain", 
    name: "Plain Dahi / Low-Fat Yogurt (1 cup)", 
    calories: 110, 
    protein: 6.0, 
    carbs: 8.5, 
    fat: 4.0, 
    fiber: 0.0, 
    category: "Sides", 
    description: "Plain unsweetened set curd made from pasteurized skimmed milk.",
    healthGrade: 'A',
    advice: "Excellent source of calcium and live probiotics that restore healthy gut bacteria and elevate digestion parameters."
  },
  { 
    id: "fruit-chaat", 
    name: "Fruit Chaat (1 bowl / 150g)", 
    calories: 130, 
    protein: 1.8, 
    carbs: 28, 
    fat: 0.2, 
    fiber: 3.8, 
    category: "Snacks", 
    description: "Assorted freshly cut apples, guavas, bananas, and melons spiced with traditional black pepper/chaat masala.",
    healthGrade: 'A',
    advice: "Extremely refreshing and high in soluble fibers and vitamins. Ensure no extra refined liquid sugar syrup is added."
  },
  { 
    id: "lassi-sweet", 
    name: "Traditional Sweet Lassi (1 glass)", 
    calories: 280, 
    protein: 5.5, 
    carbs: 34, 
    fat: 11.0, 
    fiber: 0.0, 
    category: "Drinks", 
    description: "Blended yogurt drink made with full-fat milk, sugar syrup, and sometimes malai cream toppings.",
    healthGrade: 'F',
    advice: "Massive sugar load. Spikes blood glucose instantly and loads excess liver fat. Swap for a light mint/salty buttermilk.",
    swapWith: "lassi-mint"
  },
  { 
    id: "lassi-mint", 
    name: "Mint / Salty Lassi (Buttermilk, 1 glass)", 
    calories: 95, 
    protein: 4.2, 
    carbs: 6.8, 
    fat: 3.0, 
    fiber: 0.4, 
    category: "Drinks", 
    description: "Cool thin blended yogurt beverage prepared with ice-water, black salt, and crushed mint leaves.",
    healthGrade: 'A',
    advice: "Incredible digestive aid and hydrator. Mint is cooling for body temperature and low fat keeps cardiovascular pipes clean.",
    swapWith: "lassi-mint"
  },
  { 
    id: "chai-sugar", 
    name: "Chai with Full-Milk & Sugar (1 cup)", 
    calories: 155, 
    protein: 3.2, 
    carbs: 19, 
    fat: 6.2, 
    fiber: 0.0, 
    category: "Drinks", 
    description: "Black tea boiled together with buffalo milk and white cane sugar, highly popular daily beverage.",
    healthGrade: 'D',
    advice: "Full-fat buffalo milk and refined white sugar make this beverage high in liquid calories. Swap for skimmed milk tea with zero sugar.",
    swapWith: "green-tea"
  },
  { 
    id: "green-tea", 
    name: "Cardamom Green Tea / Kahwa (1 cup)", 
    calories: 2, 
    protein: 0.0, 
    carbs: 0.0, 
    fat: 0.0, 
    fiber: 0.0, 
    category: "Drinks", 
    description: "Unsweetened hot green tea leaves brewed with cardamom pods (elaichi) and mint.",
    healthGrade: 'A',
    advice: "Zero-calorie antioxidant powerhouse. Green tea catechins boost metabolic rates and support artery flexibility."
  },
  { 
    id: "dates-khajoor", 
    name: "Dates / Khajoor (2 medium)", 
    calories: 120, 
    protein: 1.0, 
    carbs: 31, 
    fat: 0.1, 
    fiber: 3.2, 
    category: "Snacks", 
    description: "Sweet dried palm fruits, highly popular for fast-breaking and quick stamina restoration.",
    healthGrade: 'B',
    advice: "High in natural sugars but rich in potassium and dietary fibers that prevent the sugar from releasing too fast. Perfect sweet craving alternative."
  }
];
